### ISSUE TITLE
Milestones Week 43

### ISSUE THREAD

**Issue by miriamkw** [miriamkw/GluPredKit#33]
Refactoring:
- [x] Remove hour from preprocessor to parsers
- [x] Move library-specific preprocessing to model training from preprocessors (create helpers), and refactor preprocessors accordingly
- [x] Add config files defining one preprocessor, prediction horizons (list), num lagged features, num features, cat features, test size
- [x] Add the training flow using config file
- [x] Add the evaluation metrics using config file
- [x] Move error grids to evaluation metrics, but one metric can be a list
- [x] Add plots using config file
- [x] Use model names with config-file-name and ph
- [x] Add a config_manager for the config_files so that you dont need to use ['name'] which is prone to errors
- [x] Add a helper `cli` in helpers, and add methods like "getModule" for models etc. to reduce cli.py
- [x] Update all data-folders to reflect the new functionality (remove "processed", add "configurations")
- [x] Remove all outdated code

Add real-time predictions (after config, so you dont need to refactor):
- [x] Simply added a new plot that plots trajectories. This will be in real time if the input data is up to date
- [x] Plot trajectory(/ies)
- [x] Define either date "now", or a single point in time
- [x] Use names 

Update CLI:
- [x] Create config
- [x] Use config instead of preprocessor to train models (and remove preprocess)
- [x] Evaluate models should use config as well
- [x] Separate commands: "draw_plots", "calculate_metrics"
- [x] Real-time predictions

Documentation:
- [x] Explain the difference between "glupredkit" and "python -m glupredkit.cli"
- [x] Contributing with code: 
    - [x] Define output format of parser
    - [x] process of time-lagged features because it is oftern model/library-specific. 
- [x] All updates to CLI must be documented
- [x] Go specifically into real-time plots description
- [x] Create and add figures:
   - [x] Class diagram for "Contributing with code"-section
   - [x] Process diagram -- what happens inside each command?
   - [x] Update the diagram that is on the front page to reflect changes

Finish:
- [x] After rigorous testing of all functionality and usability test
- [x] upload again to PyPi
- [x] merge into main
